<div class="hero-unit">
    <h1 class="pagination-centered"><?php echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">

    <div class="span4">
        <h2><?php echo $this->translate('Ups, I did it again') ?></h2>
    </div>

    <div class="span4">
        <h2><?php echo $this->translate('Ups, I did it again') ?></h2>
   </div>

   <div class="span4">
       <h2><?php echo $this->translate('Ups, I did it again') ?></h2>
   </div>
</div>
